name: ml
channels:
  - pytorch
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - tensorflow
  - keras
  - jupyter
  - pip:
    - kaggle
    - pylint
    - featuretools
